### ISSUE TITLE
Put whiteboards in

### ISSUE THREAD

**Issue by mitar** [cloyne/hackerspace#2]
After we paint, we should put the whiteboards on all reasonable walls. So top-to-bottom sized whiteboards directly to the wall, to cover whole wall, without even boarders.

@spencerhitch can you take over buying the necessary whiteboards?

**Comment by cotnerca** [comment]
http://moorecoinc.com/product-view.php?category=combo-reversible-189&series=adjustable-modular-boards-597

@nerdynucleon

**Comment by cotnerca** [comment]
http://www.skydesign.com/products/magnetic-markerglass/vitracolor-magnetic-markerglass

**Comment by cotnerca** [comment]
http://property.berkeley.edu/uc-berkeley-surplus

**Comment by nerdynucleon** [comment]
http://www.staples.com/Quartet-Melamine-Dry-Erase-Board-with-Aluminum-Frame-8-x-4/product_789834?externalize=certona#id='dropdown_18848'

**Comment by nerdynucleon** [comment]
http://www.amazon.com/Grande-High-Boards-Porcelain-Markerboard/dp/B001G9X9FW

**Comment by nerdynucleon** [comment]
movable whiteboards: 800.749.2258

**Comment by cotnerca** [comment]
We need to decide whether we want to keep the whiteboards that were previously purchased, save them for another project in the house or to just to get rid of them.

**Comment by cotnerca** [comment]
PVC pipe as rollers?

**Comment by emilynathan** [comment]
WE DID IIIIITTTTT~~~~

**Comment by sunnysideofthescreen** [comment]
close that shit
