### ISSUE TITLE
add shelves into the back storage space

### ISSUE THREAD

**Issue by cotnerca** [cloyne/hackerspace#20]

**Comment by mitar** [comment]
We didn't really do that, but OK. ;-)

**Comment by emilynathan** [comment]
I thought this meant the makercloset

**Comment by mitar** [comment]
No, the idea for this is to put shelves at the end, where each shelf has your stuff/project you are working on. And then you can take the shelf down and put it on the table and work, and then you can put it back when you finish. A pretty neat thing I learned in one other hackerspace.
