### ISSUE TITLE
Bug when updating date of event

### ISSUE THREAD

**Issue by noshaf** [cloyne/hackerspace#32]
When you change the calendar date in edit view it does not reset when you go to another event, so if you just try to update the title of an event after you changed the date of another, when you hit update it will take the calendar date from before

**Comment by noshaf** [comment]
Wrong git repo loool

**Comment by mitar** [comment]
Which one is the correct one?

**Comment by noshaf** [comment]
My Gather Android repository (the app that I have been building)

**Comment by mitar** [comment]
Ha ha. I am proud that you got to our repository. :-)
